# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_merge_20170628_0905'),
    ]

    operations = [
    ]
