# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20170709_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ProjectPhaseLog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects_projectphaselog_project_related', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='ProjectPhaseLog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects_projectphaselog_status_related', to='bb_projects.ProjectPhase'),
        ),
    ]
