# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20170709_1847'),
        ('projects', '0042_merge_20170920_1332'),
    ]

    operations = [
    ]
