# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-16 08:52
from __future__ import unicode_literals

from django.db import migrations
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps):
    group_perms = {
        'Staff': {
            'perms': (
                'change_projectbankaccount',
            )
        },
    }

    update_group_permissions('projects', group_perms, apps)


def migrate_bank_account(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectBankAccount = apps.get_model('projects', 'ProjectBankAccount')
    add_group_permissions(apps)

    for project in Project.objects.all():
        ProjectBankAccount.objects.create(
            project=project,
            name=project.account_holder_name,
            address=project.account_holder_address,
            postal_code=project.account_holder_postal_code,
            city=project.account_holder_city,
            country=project.account_holder_country,
            number=project.account_number,
            details=project.account_details,
            bank_country=project.account_bank_country,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20180516_0954'),
    ]

    operations = [
        migrations.RunPython(migrate_bank_account)
    ]
