# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 17:17
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_merge_20170628_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, help_text='Task location (leave empty for anywhere/online)', max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='resume',
            field=bluebottle.utils.fields.PrivateFileField(blank=True, upload_to=b'private/private/private/task-members/resume'),
        ),
        migrations.AlterField(
            model_name='taskmemberstatuslog',
            name='task_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_taskmemberstatuslog_related', to='tasks.TaskMember'),
        ),
        migrations.AlterField(
            model_name='taskstatuslog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_taskstatuslog_related', to='tasks.Task'),
        ),
    ]
