# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20170706_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE,
                                    related_name='tasks_task_project_related', to='projects.Project'),
        )
    ]
