# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20170709_2046'),
        ('tasks', '0035_merge_20170831_1449'),
    ]

    operations = [
    ]
