from decimal import Decimal

from django.db import models
from django.utils.translation import ugettext as _

from bluebottle.payments.models import Payment


class SafaricomPayment(Payment):

    """
    BusinessShortCode	The organization shortcode used to receive the transaction.
    Password	The password for encrypting the request. This is generated by base64 encoding
                BusinessShortcode, Passkey and Timestamp.
    Timestamp	The timestamp of the transaction in the format yyyymmddhhiiss.
    TransactionType	The transaction type to be used for this request. Only CustomerPayBillOnline is supported.
    Amount	The amount to be transacted.
    PartyA	The MSISDN sending the funds.
    PartyB	The organization shortcode receiving the funds
    PhoneNumber	The MSISDN sending the funds.
    CallBackURL	The url to where responses from M-Pesa will be sent to.
    AccountReference	Used with M-Pesa PayBills.
    TransactionDesc	A description of the transaction.
    """

    business_short_code = models.CharField(
        help_text="TThe organization shortcode used to receive the transaction.",
        null=True, blank=True,
        max_length=200)
    transaction_type = models.CharField(
        help_text="The transaction type to be used for this request.",
        default="CustomerPayBillOnline",
        null=True, blank=True,
        max_length=200)
    amount = models.CharField(
        help_text="Amount",
        null=True, blank=True,
        max_length=200)
    party_a = models.CharField(
        help_text="The MSISDN sending the funds.",
        null=True, blank=True,
        max_length=100)
    party_b = models.CharField(
        help_text="The organization shortcode receiving the funds",
        null=True, blank=True,
        max_length=100)
    phone_number = models.CharField(
        help_text="The MSISDN sending the funds.",
        null=True, blank=True,
        max_length=100)
    call_back_url = models.CharField(
        help_text="The url to where responses from M-Pesa will be sent to.",
        null=True, blank=True,
        max_length=200)
    account_reference = models.CharField(
        help_text=_('Used with M-Pesa PayBills.'),
        null=True, blank=True,
        max_length=200)

    response = models.TextField(
        help_text=_('Result from Safaricom (status update)'),
        null=True, blank=True)

    update_response = models.TextField(
        help_text=_('Result from Safaricom (status update)'),
        null=True, blank=True)

    class Meta:
        ordering = ('-created', '-updated')
        verbose_name = "Safaricom/Mpesa Payment"
        verbose_name_plural = "Safaricom/Mpesa Payments"

    def get_method_name(self):
        """ Return the payment method name."""
        return 'safaricom'

    def get_fee(self):
        """
        Not sure about the fee yet.
        """
        fee = round(self.order_payment.amount * Decimal(0.05), 2)
        return fee
