# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:55
from __future__ import unicode_literals

import bluebottle.cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'article', wagtail.wagtailcore.blocks.StructBlock(
                    [(b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)),
                     (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()),
                     (b'text', wagtail.wagtailcore.blocks.RichTextBlock(required=False))])), (b'block_items',
                                                                                              wagtail.wagtailcore.blocks.StructBlock(
                                                                                                  [(b'title',
                                                                                                    wagtail.wagtailcore.blocks.TextBlock(
                                                                                                        required=False)),
                                                                                                   (b'intro',
                                                                                                    wagtail.wagtailcore.blocks.TextBlock(
                                                                                                        required=False)),
                                                                                                   (b'blocks',
                                                                                                    wagtail.wagtailcore.blocks.ListBlock(
                                                                                                        wagtail.wagtailcore.blocks.StructBlock(
                                                                                                            [(b'image',
                                                                                                              wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                             (b'title',
                                                                                                              wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                  required=False)),
                                                                                                             (b'text',
                                                                                                              wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                  required=False))]),
                                                                                                        icon=b'image',
                                                                                                        template=b'pages/blocks/projects.html')),
                                                                                                   (b'button',
                                                                                                    wagtail.wagtailcore.blocks.StructBlock(
                                                                                                        [(b'title',
                                                                                                          wagtail.wagtailcore.blocks.TextBlock(
                                                                                                              required=True)),
                                                                                                         (b'url',
                                                                                                          wagtail.wagtailcore.blocks.TextBlock(
                                                                                                              required=True))],
                                                                                                        required=False))])),
                                                                 (b'projects', wagtail.wagtailcore.blocks.StructBlock([(
                                                                                                                       b'title',
                                                                                                                       wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                           required=False)),
                                                                                                                       (
                                                                                                                       b'projects',
                                                                                                                       wagtail.wagtailcore.blocks.ListBlock(
                                                                                                                           bluebottle.cms.blocks.ProjectChooserBlock()))])),
                                                                 (b'heading', wagtail.wagtailcore.blocks.CharBlock(
                                                                     classname=b'full title', icon=b'title')), (
                                                                 b'paragraph',
                                                                 wagtail.wagtailcore.blocks.RichTextBlock()), (b'image',
                                                                                                               wagtail.wagtailimages.blocks.ImageChooserBlock(
                                                                                                                   icon=b'image')),
                                                                 (b'step_blocks',
                                                                  bluebottle.cms.blocks.SectionListBlock(
                                                                      wagtail.wagtailcore.blocks.StructBlock([(b'image',
                                                                                                               wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                              (b'title',
                                                                                                               wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                   required=False)),
                                                                                                              (b'text',
                                                                                                               wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                   required=False))]),
                                                                      icon=b'image',
                                                                      template=b'pages/blocks/projects.html')), (
                                                                 b'one_section', wagtail.wagtailcore.blocks.StructBlock(
                                                                     [(b'image',
                                                                       wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                      (b'title', wagtail.wagtailcore.blocks.TextBlock(
                                                                          required=False)), (b'text',
                                                                                             wagtail.wagtailcore.blocks.TextBlock(
                                                                                                 required=False)), (
                                                                      b'action', wagtail.wagtailcore.blocks.StructBlock(
                                                                          [(b'title',
                                                                            wagtail.wagtailcore.blocks.TextBlock(
                                                                                required=True)), (b'url',
                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                      required=True))],
                                                                          required=False))])), (b'video',
                                                                                                wagtail.wagtailcore.blocks.StructBlock(
                                                                                                    [(b'title',
                                                                                                      wagtail.wagtailcore.blocks.TextBlock(
                                                                                                          required=False)),
                                                                                                     (b'url',
                                                                                                      wagtail.wagtailcore.blocks.URLBlock(
                                                                                                          required=False)),
                                                                                                     (
                                                                                                     b'background_image',
                                                                                                     wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                     (b'button_text',
                                                                                                      wagtail.wagtailcore.blocks.TextBlock(
                                                                                                          required=False))],
                                                                                                    icon=b'media'))],
                                                                null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
