# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:04
from __future__ import unicode_literals

import bluebottle.cms.blocks
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0002_resultspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultspage',
            name='end_date',
            field=models.DateField(default=2014),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultspage',
            name='start_date',
            field=models.DateField(default=1973),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'article', wagtail.wagtailcore.blocks.StructBlock(
                [(b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)),
                 (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()),
                 (b'text', wagtail.wagtailcore.blocks.RichTextBlock(required=False))])), (b'block_items',
                                                                                          wagtail.wagtailcore.blocks.StructBlock(
                                                                                              [(b'title',
                                                                                                wagtail.wagtailcore.blocks.TextBlock(
                                                                                                    required=False)), (
                                                                                               b'intro',
                                                                                               wagtail.wagtailcore.blocks.TextBlock(
                                                                                                   required=False)), (
                                                                                               b'blocks',
                                                                                               wagtail.wagtailcore.blocks.ListBlock(
                                                                                                   wagtail.wagtailcore.blocks.StructBlock(
                                                                                                       [(b'image',
                                                                                                         wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                        (b'title',
                                                                                                         wagtail.wagtailcore.blocks.TextBlock(
                                                                                                             required=False)),
                                                                                                        (b'text',
                                                                                                         wagtail.wagtailcore.blocks.TextBlock(
                                                                                                             required=False))]),
                                                                                                   icon=b'image',
                                                                                                   template=b'pages/blocks/projects.html')),
                                                                                               (b'button',
                                                                                                wagtail.wagtailcore.blocks.StructBlock(
                                                                                                    [(b'title',
                                                                                                      wagtail.wagtailcore.blocks.TextBlock(
                                                                                                          required=True)),
                                                                                                     (b'url',
                                                                                                      wagtail.wagtailcore.blocks.TextBlock(
                                                                                                          required=True))],
                                                                                                    required=False))])),
                                                          (b'projects', wagtail.wagtailcore.blocks.StructBlock([(
                                                                                                                b'title',
                                                                                                                wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                    required=False)),
                                                                                                                (
                                                                                                                b'projects',
                                                                                                                wagtail.wagtailcore.blocks.ListBlock(
                                                                                                                    bluebottle.cms.blocks.ProjectChooserBlock()))])),
                                                          (b'statistics', wagtail.wagtailcore.blocks.StructBlock([(
                                                                                                                  b'title',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  b'projects',
                                                                                                                  wagtail.wagtailcore.blocks.ListBlock(
                                                                                                                      wagtail.wagtailcore.blocks.StructBlock(
                                                                                                                          [
                                                                                                                              (
                                                                                                                              b'title',
                                                                                                                              wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                                  required=False)),
                                                                                                                              (
                                                                                                                              b'type',
                                                                                                                              wagtail.wagtailcore.blocks.ChoiceBlock(
                                                                                                                                  choices=[
                                                                                                                                      (
                                                                                                                                      b'manual',
                                                                                                                                      'Manual'),
                                                                                                                                      (
                                                                                                                                      b'donated_total',
                                                                                                                                      'Donated total'),
                                                                                                                                      (
                                                                                                                                      b'projects_realized',
                                                                                                                                      'Projects realised'),
                                                                                                                                      (
                                                                                                                                      b'tasks_realized',
                                                                                                                                      'Tasks realised'),
                                                                                                                                      (
                                                                                                                                      b'people_involved',
                                                                                                                                      'People involved'),
                                                                                                                                      (
                                                                                                                                      b'votes_cast',
                                                                                                                                      'Number of votes cast')])),
                                                                                                                              (
                                                                                                                              b'value',
                                                                                                                              wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                                  required=False))])))])),
                                                          (b'heading',
                                                           wagtail.wagtailcore.blocks.CharBlock(classname=b'full title',
                                                                                                icon=b'title')),
                                                          (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (
                                                          b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(
                                                              icon=b'image')), (b'step_blocks',
                                                                                bluebottle.cms.blocks.SectionListBlock(
                                                                                    wagtail.wagtailcore.blocks.StructBlock(
                                                                                        [(b'image',
                                                                                          wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                         (b'title',
                                                                                          wagtail.wagtailcore.blocks.TextBlock(
                                                                                              required=False)), (
                                                                                         b'text',
                                                                                         wagtail.wagtailcore.blocks.TextBlock(
                                                                                             required=False))]),
                                                                                    icon=b'image',
                                                                                    template=b'pages/blocks/projects.html')),
                                                          (b'one_section', wagtail.wagtailcore.blocks.StructBlock([(
                                                                                                                   b'image',
                                                                                                                   wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                                   (
                                                                                                                   b'title',
                                                                                                                   wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   b'text',
                                                                                                                   wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   b'action',
                                                                                                                   wagtail.wagtailcore.blocks.StructBlock(
                                                                                                                       [
                                                                                                                           (
                                                                                                                           b'title',
                                                                                                                           wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                               required=True)),
                                                                                                                           (
                                                                                                                           b'url',
                                                                                                                           wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                               required=True))],
                                                                                                                       required=False))])),
                                                          (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'title',
                                                                                                              wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                  required=False)),
                                                                                                             (b'url',
                                                                                                              wagtail.wagtailcore.blocks.URLBlock(
                                                                                                                  required=False)),
                                                                                                             (
                                                                                                             b'background_image',
                                                                                                             wagtail.wagtailimages.blocks.ImageChooserBlock()),
                                                                                                             (
                                                                                                             b'button_text',
                                                                                                             wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                 required=False))],
                                                                                                            icon=b'media'))],
                                                         null=True),
        ),
    ]
