# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 15:16
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_auto_20171128_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('logo', bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to=b'logo/', verbose_name='logo')),
                ('primary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color_shadow', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_color_shadow', models.CharField(blank=True, max_length=100, null=True)),
                ('gray_color', models.CharField(blank=True, max_length=100, null=True)),
                ('white_color', models.CharField(blank=True, max_length=100, null=True)),
                ('header_background_color', models.CharField(blank=True, max_length=100, null=True)),
                ('modal_background_color', models.CharField(blank=True, max_length=100, null=True)),
                ('header_logo_link_padding', models.CharField(blank=True, max_length=100, null=True)),
                ('header_logo_link_padding_scroll', models.CharField(blank=True, max_length=100, null=True)),
                ('font_family', models.CharField(blank=True, max_length=100, null=True)),
                ('h1_font_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('h2_font_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('h3_font_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('h4_font_weight', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
