# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_styleplatformsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='gray_color',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='h1_font_weight',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='h2_font_weight',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='h3_font_weight',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='h4_font_weight',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='header_background_color',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='header_logo_link_padding',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='header_logo_link_padding_scroll',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='modal_background_color',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='primary_color_shadow',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='secondary_color_shadow',
        ),
        migrations.RemoveField(
            model_name='styleplatformsettings',
            name='white_color',
        ),
        migrations.AddField(
            model_name='stylerule',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.StylePlatformSettings'),
        ),
    ]
