# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 14:21
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations

from bluebottle.analytics.utils import create_report_views


def create_views(apps, schema_editor):
    create_report_views()

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20171031_1209'),
        ('clients', '0001_initial'),
        ('projects', '0044_auto_20171110_1549'),
        ('tasks', '0035_merge_20170831_1449'),
        ('geo', '0004_auto_20160929_0817'),
    ]

    operations = [
        migrations.RunPython(create_views)
    ]
